#!/bin/bash
# copies all necessary files in this directory to the var folder 
SITE=/var/www/html/equine

if test -e "$SITE"; then
	sudo rm -r $SITE
fi
sudo mkdir $SITE
sudo cp *.php  $SITE
sudo cp -r assets $SITE
#sudo cp *.html /var/www/html/ 
