#!/bin/bash
# copies all necessary files in this directory to the var folder 
SITE=/var/www/html/equine/

if test -e "$SITE"; then
	sudo rm -r $SITE
fi
sudo mkdir $SITE
sudo cp -r ../equine/* $SITE #copy all files from equine folder to the site folder